// Generated by CoffeeScript 1.6.3
(function() {
  exports.index = function(req, res) {
    return res.render('index', {
      sitetitle: 'MyWebsite'
    });
  };

  exports.about = function(req, res) {
    console.log('comming about');
    return res.render('index', {
      sitetitle: 'About'
    });
  };

}).call(this);
