// Generated by CoffeeScript 1.6.3
(function() {
  exports.list = function(req, res) {
    return res.send('respond with a resource');
  };

  exports.get = function(req, res) {
    return res.send("user id: " + req.params.id);
  };

}).call(this);
