// Generated by CoffeeScript 1.6.3
(function() {
  var fs;

  fs = require('fs');

  exports.list = function(req, res) {
    return res.send('respond with a resource');
  };

  exports.get = function(req, res) {
    return res.send("user id: " + req.params.id);
  };

  exports.saveFile = function(req, res) {
    var data;
    data = 'Some data I want to write to a file!';
    return fs.writeFile("public\\file\\file.txt", data, function(err) {
      if (!err) {
        console.log('wrote data to file.txt');
        return res.send('wrote data to file.txt');
      } else {
        throw err;
      }
    });
  };

}).call(this);
